name: Update swaggerui

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go run generate.go

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Update swwaggerui"
        commit-message: "feat: update swaggerui"
        author: Github Workflow <noreply@github.com>
        delete-branch: true
